## Using Pymongo Lesson 2


#### Connect to MongoDB server

Start your MongoDB server
Connect to the MongoDB server

#### Task 1
Connect to the MongoDB server.

In [1]:
from pymongo import MongoClient

client = MongoClient('localhost', 27017)

#### Find all documents in the collection

* Using find() to list `all` documents in a collection.

    ```
    db = client.mydatabase
    for document in db.mycollection.find():
        print(document)
    ```
 
* If you are only interested in the first match for a given query, or if you know the database only contains one matching document, you can use `find_one()`.

#### Find documents in the collection with conditions/filters
Projection in MongoDB follows some basic rules:

- The `_id` field is always included unless explicitly excluded. 
- Specifying a field for inclusion implicitly excludes all other fields except the `_id` field.
    
    ```
    db = client.mydatabase
    query = {"age": {"$gt":20}}  ## filter for age greater than 20
    projections ={"_id":0}
    
    result = db.books.find(query, projections)
    for x in result:
        print(x)   
    ```

#### Task 2
List all the books in bookdb. Display the books in the format as shown. 
Note: Resolved any errors if any.

```
S/N   Title                                                        ISBN                
1     Unlocking Android                                            1933988673          
2     Android in Action, Second Edition                            1935182722          
3     Specification by Example                                     1617290084          
4     Flex 3 in Action                                             1933988746          
5     Flex 4 in Action                                             1935182420          
6     Collective Intelligence in Action                            1933988312          
7     Zend Framework in Action                                     1933988320          
8     Flex on Java                                                 1933988797          
9     Griffon in Action                                            1935182234          
10    OSGi in Depth                                                193518217X          
11    Flexible Rails                                               1933988509          
12    Hello! Flex 4                                                1933988762          
13    Coffeehouse                                                  1884777384          
  .... .....       
 
``` 

In [34]:
bookdb = client['bookdb']
books = bookdb['books']

query = {"title": {"$exists": True}}
proj = {"title": 1, "isbn": 1}

for book in books.find(query, proj):
    print(book)

{'_id': 1, 'title': 'Unlocking Android', 'isbn': '1933988673'}
{'_id': 2, 'title': 'Android in Action, Second Edition', 'isbn': '1935182722'}
{'_id': 3, 'title': 'Specification by Example', 'isbn': '1617290084'}
{'_id': 4, 'title': 'Flex 3 in Action', 'isbn': '1933988746'}
{'_id': 5, 'title': 'Flex 4 in Action', 'isbn': '1935182420'}
{'_id': 6, 'title': 'Collective Intelligence in Action', 'isbn': '1933988312'}
{'_id': 7, 'title': 'Zend Framework in Action', 'isbn': '1933988320'}
{'_id': 8, 'title': 'Flex on Java', 'isbn': '1933988797'}
{'_id': 9, 'title': 'Griffon in Action', 'isbn': '1935182234'}
{'_id': 10, 'title': 'OSGi in Depth', 'isbn': '193518217X'}
{'_id': 11, 'title': 'Flexible Rails', 'isbn': '1933988509'}
{'_id': 13, 'title': 'Hello! Flex 4', 'isbn': '1933988762'}
{'_id': 14, 'title': 'Coffeehouse', 'isbn': '1884777384'}
{'_id': 15, 'title': 'Team Foundation Server 2008 in Action', 'isbn': '1933988592'}
{'_id': 16, 'title': 'Brownfield Application Development in .NET', 'isb

 #### Task 3
 
List the first 10 books with more than 600 pages. Display the documents as shown.
The result should be sorted by page count in ascending order.
```
Title                                              Page count          
wxPython in Action                                 620                 
Seam in Action                                     624                 
XDoclet in Action                                  624                 
Art of Java Web Development                        624                 
GWT in Action                                      632                 
Microsoft Reporting Services in Action             656                 
JSP Tag Libraries                                  656                 
Java Development with Ant                          672                 
Struts in Action                                   672                 
Ajax in Action                                     680                                       
```

In [23]:
query = {"pageCount": {"$gt": 600}}
proj = {"_id": 0, "title": 1, "pageCount": 1}

for book in books.find(query, proj).sort("pageCount", 1).limit(10):
  print(book)

{'title': 'wxPython in Action', 'pageCount': 620}
{'title': 'Seam in Action', 'pageCount': 624}
{'title': 'XDoclet in Action', 'pageCount': 624}
{'title': 'Art of Java Web Development', 'pageCount': 624}
{'title': 'GWT in Action', 'pageCount': 632}
{'title': 'Microsoft Reporting Services in Action', 'pageCount': 656}
{'title': 'JSP Tag Libraries', 'pageCount': 656}
{'title': 'Java Development with Ant', 'pageCount': 672}
{'title': 'Struts in Action', 'pageCount': 672}
{'title': 'Ajax in Action', 'pageCount': 680}


#### Task 4
Find books with categories that only contains **Java**.
Display the first 10 documents as shown.
The result should be sorted by title
```
Title                                                        ISBN                
ActiveMQ in Action                                           1933988940           
Android in Action, Second Edition                            1935182722           
Ant in Action                                                193239480X           
AspectJ in Action                                            1930110936           
AspectJ in Action, Second Edition                            1933988053           
Camel in Action                                              1935182366           
Clojure in Action                                            1935182595           
Command-line Processing with CLI                             1932394524l-e        
Distributed Programming with Java                            1884777651           
Domino Development with Java                                 1930110049                    
```

In [32]:
query = {"categories": ["Java"]}
proj = {"_id": 0, "title": 1, "isbn": 1}

for book in books.find(query, proj).sort("title", 1).limit(10):
  print(book)

{'title': 'ActiveMQ in Action', 'isbn': '1933988940'}
{'title': 'Android in Action, Second Edition', 'isbn': '1935182722'}
{'title': 'Ant in Action', 'isbn': '193239480X'}
{'title': 'AspectJ in Action', 'isbn': '1930110936'}
{'title': 'AspectJ in Action, Second Edition', 'isbn': '1933988053'}
{'title': 'Camel in Action', 'isbn': '1935182366'}
{'title': 'Clojure in Action', 'isbn': '1935182595'}
{'title': 'Command-line Processing with CLI', 'isbn': '1932394524l-e'}
{'title': 'Distributed Programming with Java', 'isbn': '1884777651'}
{'title': 'Domino Development with Java', 'isbn': '1930110049'}


#### Task 5
Find books with categories that contains **Java** (Java only or Java and others).
Display the first 10 documents as shown.
The result should be sorted by title
```
Title                                                        ISBN                
3D User Interfaces with Java 3D                              1884777902          
ActiveMQ in Action                                           1933988940          
Android in Action, Second Edition                            1935182722          
Ant in Action                                                193239480X          
AspectJ in Action                                            1930110936          
AspectJ in Action, Second Edition                            1933988053          
Bitter EJB                                                   1930110952          
Bitter Java                                                  193011043X          
Camel in Action                                              1935182366          
Clojure in Action                                            1935182595                   
```

In [33]:
query = {"categories": {"$in": ["Java"]}}
proj = {"_id": 0, "title": 1, "isbn": 1}

for book in books.find(query, proj).sort("title", 1).limit(10):
  print(book)

{'title': '3D User Interfaces with Java 3D', 'isbn': '1884777902'}
{'title': 'ActiveMQ in Action', 'isbn': '1933988940'}
{'title': 'Android in Action, Second Edition', 'isbn': '1935182722'}
{'title': 'Ant in Action', 'isbn': '193239480X'}
{'title': 'AspectJ in Action', 'isbn': '1930110936'}
{'title': 'AspectJ in Action, Second Edition', 'isbn': '1933988053'}
{'title': 'Bitter EJB', 'isbn': '1930110952'}
{'title': 'Bitter Java', 'isbn': '193011043X'}
{'title': 'Camel in Action', 'isbn': '1935182366'}
{'title': 'Clojure in Action', 'isbn': '1935182595'}


#### Task 6
Find books with categories contains both **Java** and **Internet**. Display the first 10 documents as shown.
The result should be sorted by page count in descending order and title in ascending order.
```
Title                                    Categories                               Page Count
Swing Second Edition                     Java, Internet                           912  
Java Development with Ant                Java, Internet                           672  
Struts in Action                         Java, Internet                           672  
JSP Tag Libraries                        Java, Internet                           656  
GWT in Action                            Internet, Java                           632  
Server-Based Java Programming            Java, Client-Server, Internet            592  
Tapestry in Action                       Java, Internet                           580  
Java Servlets by Example                 Java, Internet                           550  
Java 2 Micro Edition                     Java, Internet                           504  
Bitter EJB                               Java, Internet                           440  
JDK 1.4 Tutorial                         Java, Internet                           408  
Instant Messaging in Java                Internet, Java                           402  
Java 3D Programming                      Java, Internet, Computer Graph           400                             
```

In [40]:
query = {"categories": {"$all": ["Java", "Internet"]}}
proj = {"_id": 0, "title": 1, "categories": 1, "pageCount": 1}

for book in books.find(query, proj).sort([("pageCount", -1), ("title", 1)]).limit(10):
  print(book)

{'title': 'Swing Second Edition', 'pageCount': 912, 'categories': ['Java', 'Internet']}
{'title': 'Java Development with Ant', 'pageCount': 672, 'categories': ['Java', 'Internet']}
{'title': 'Struts in Action', 'pageCount': 672, 'categories': ['Java', 'Internet']}
{'title': 'JSP Tag Libraries', 'pageCount': 656, 'categories': ['Java', 'Internet']}
{'title': 'GWT in Action', 'pageCount': 632, 'categories': ['Internet', 'Java']}
{'title': 'Server-Based Java Programming', 'pageCount': 592, 'categories': ['Java', 'Client-Server', 'Internet']}
{'title': 'Tapestry in Action', 'pageCount': 580, 'categories': ['Java', 'Internet']}
{'title': 'Java Servlets by Example', 'pageCount': 550, 'categories': ['Java', 'Internet']}
{'title': 'Java 2 Micro Edition', 'pageCount': 504, 'categories': ['Java', 'Internet']}
{'title': 'Bitter EJB', 'pageCount': 440, 'categories': ['Java', 'Internet']}


#### Task 7

Find books with categories containing Java only and has author's information and pageCount greater than 550.
Display the first 15 documents as shown with at most 2 authors displayed. The document should be sorted by page count in descending order and title in ascending order.
```
Title                                    Page Count Categories                 Author/s  
Java Foundation Classes                  1088       Java                       Stephen C. Drye, William C. Wake 
Java Persistence with Hibernate          880        Java                       Christian Bauer, Gavin King 
Java Network Programming, Second Edition 860        Java                       Merlin Hughes, Michael Shoffner 
Spring in Action, Second Edition         768        Java                       Craig Walls with Ryan Breidenbach 
JUnit Recipes                            752        Java                       J. B. Rainsberger with contributions by Scott Stirling 
JavaServer Faces in Action               744        Java                       Kito D. Mann 
EJB 3 in Action                          712        Java                       Debu Panda, Reza Rahman 
Groovy in Action, Second Edition         700        Java                       Dierk KÃ¶nig, Guillaume Laforge 
Groovy in Action                         696        Java                       Dierk Koenig with Andrew Glover, Paul King 
Seam in Action                           624        Java                       Dan Allen  
Ant in Action                            600        Java                       Steve Loughran, Erik Hatcher 
iText in Action, Second Edition          600        Java                       Bruno Lowagie 
Android in Action, Second Edition        592        Java                       W. Frank Ableson, Robi Sen 
POJOs in Action                          592        Java                       Chris Richardson 
AspectJ in Action, Second Edition        568        Java                       Ramnivas Laddad 
```

In [41]:
query = {"categories": ["Java"], "pageCount": {"$gt": 550 }}
proj = {"_id": 0, "title": 1, "pageCount": 1, "categories": 1, "authors": 1}

for book in books.find(query, proj).sort([("pageCount", -1), ("title", 1)]).limit(15):
  book['authors'] = book['authors'][:2]  # Show at most 2 authors
  print(book)

{'title': 'Java Foundation Classes', 'pageCount': 1088, 'authors': ['Stephen C. Drye', 'William C. Wake'], 'categories': ['Java']}
{'title': 'Java Persistence with Hibernate', 'pageCount': 880, 'authors': ['Christian Bauer', 'Gavin King'], 'categories': ['Java']}
{'title': 'Java Network Programming, Second Edition', 'pageCount': 860, 'authors': ['Merlin Hughes', 'Michael Shoffner'], 'categories': ['Java']}
{'title': 'Spring in Action, Second Edition', 'pageCount': 768, 'authors': ['Craig Walls with Ryan Breidenbach'], 'categories': ['Java']}
{'title': 'JUnit Recipes', 'pageCount': 752, 'authors': ['J. B. Rainsberger with contributions by Scott Stirling'], 'categories': ['Java']}
{'title': 'JavaServer Faces in Action', 'pageCount': 744, 'authors': ['Kito D. Mann'], 'categories': ['Java']}
{'title': 'EJB 3 in Action', 'pageCount': 712, 'authors': ['Debu Panda', 'Reza Rahman'], 'categories': ['Java']}
{'title': 'Groovy in Action, Second Edition', 'pageCount': 700, 'authors': ['Dierk KÃ¶ni

#### Task 8

Find books with categories containing Java and has author's information and has 400, 500 or 600 pages.
Display the documents as shown with 1 author displayed. The document should be sorted by page count in descending order and title in ascending order.
```
Title                                    Page Count Categories                 Author    
Ant in Action                            600        Java                       Steve Loughran 
iText in Action, Second Edition          600        Java                       Bruno Lowagie 
Portlets and Apache Portals              500        Java                       Stefan Hepper 
Spring Roo in Action                     500        Java                       Ken Rimple 
The Awesome Power of Java Beans          500        Java                       Lawrence H. Rodrigues 
Hibernate in Action                      400        Java                       Christian Bauer 
Hibernate in Action (Chinese Edition)    400        Java                       Christian Bauer 
```

In [44]:
query = {"categories": {"$in": ["Java"]}, "pageCount": {"$in": [400, 500, 600]}}
proj = {"_id": 0, "title": 1, "pageCount": 1, "categories": 1, "authors": 1}

for book in books.find(query, proj).sort([("pageCount", -1), ("title", 1)]):
  book['authors'] = book['authors'][0]
  print(book)

{'title': 'Ant in Action', 'pageCount': 600, 'authors': 'Steve Loughran', 'categories': ['Java']}
{'title': 'Spring in Practice', 'pageCount': 600, 'authors': 'Willie Wheeler with Joshua White', 'categories': ['Java', 'Software Development']}
{'title': 'iText in Action, Second Edition', 'pageCount': 600, 'authors': 'Bruno Lowagie', 'categories': ['Java']}
{'title': 'Portlets and Apache Portals', 'pageCount': 500, 'authors': 'Stefan Hepper', 'categories': ['Java']}
{'title': 'Spring Roo in Action', 'pageCount': 500, 'authors': 'Ken Rimple', 'categories': ['Java']}
{'title': 'The Awesome Power of Java Beans', 'pageCount': 500, 'authors': 'Lawrence H. Rodrigues', 'categories': ['Java']}
{'title': 'Hibernate in Action', 'pageCount': 400, 'authors': 'Christian Bauer', 'categories': ['Java']}
{'title': 'Hibernate in Action (Chinese Edition)', 'pageCount': 400, 'authors': 'Christian Bauer', 'categories': ['Java']}
{'title': 'Java 3D Programming', 'pageCount': 400, 'authors': 'Daniel Selman', 